@startuml
left to right direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

title ИТ система компании «Будущее 2.0» через год

Person(Employee, "Сотрудник", "Администратор, аналитик и тд")

System_Boundary(CompanySystem, "ИТ система компании «Будущее 2.0»") {
    Container(UiEmployee, "Витрина Данных. Портал самообслуживания", "React/TypeScript", "Веб-портал для аналитики и отчетов")
    Container(AiServices, "AI сервисы", "AI", "AI сервисы на Python")
    Container(Kafka, "Шина событий", "Kafka", "Асинхронное взаимодействие сервисов")
    System_Boundary(DataLakehouse, "Data Lakehouse") {
        Container(ApacheIceberg, "Apache Iceberg", "Apache Iceberg", "Взаимодействие с таблицами")
        Container(Nessie, "Nessie", "Nessie", "Каталог хранения указателей на актуальные файлы метаданных")
        ContainerDb(Minio, "S3 хранилище", "Minio ", "Хранилище данных")
    }
}

Rel(Employee, UiEmployee, "Взаимодействие с порталом самообслуживания", "HTTPS")
Rel(UiEmployee, DataLakehouse, "Работа с данными", "HTTPS")
Rel(UiEmployee, Kafka, "Асинхронные задачи через шину событий", "HTTPS")
Rel(AiServices, Kafka, "Асинхронное взаимодействие через шину событий", "HTTPS")
@enduml